Repository anandadwipra/ecanteen, pull requests merged in 2021-10, with the labels that each got.

#1 Add_image Files | Preview UserMan
  img/2021-10-04-115250_1320x661_scrot.png
Labels: documentation, hacktoberfest-accepted

#2 Adding Instruction Readme.md
  README.md
  img/Readme.md
  installation/Readme.md
Labels: documentation, help wanted, hacktoberfest-accepted

#3 create ayya1
  img/vitriawidiasari.html
Labels: hacktoberfest-accepted, html
